### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by prodia4** [moon920110/canvearth#30]
Regarding the tests(I only checked the part in ServerInterfaceTest as this pull request has not been merged yet), They definitely pass, but when I bring the same logic to the app and actually run it, ANR happens.(When the UI thread of an Android app is blocked for too long, an "Application Not Responding" (ANR) error is triggered.)

**Comment by inyukwo1** [comment]
@prodia4 In `ServerInterfaceTest`, I used `writePixelSync` and `getBitmapSync`, which are synchronous functions that can block main thread. I used these synchronous functions because of ease of unit testing. (In fact, almost synchronous functions are for just testing.) Please prefer async versions of the methods in the app side.
